training_website/courses/urls.py
from django.urls import path
from .views import (
    CourseListView,
    CourseDetailView,
    CourseCreateView,
    CourseUpdateView,
    CourseDeleteView
)

app_name = 'courses'



urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<int:pk>/', CourseDetailView.as_view(), name='detail'),
    path('create/', CourseCreateView.as_view(), name='create'),
    path('<int:pk>/update/', CourseUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', CourseDeleteView.as_view(), name='delete'),
]
"""
urlpatterns = [
    path('', CourseListView.as_view(), name='course_list'),
    path('<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('create/', CourseCreateView.as_view(), name='course_create'),
    path('<int:pk>/update/', CourseUpdateView.as_view(), name='course_update'),
    path('<int:pk>/delete/', CourseDeleteView.as_view(), name='course_delete'),
]
"""

training_website/training_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),   # Пространство имен для модуля курсов
    # обязательно указывать префикс '/courses/'
]

training_website/templates/_navbar.html
<nav>
    <ul>
        <li><a href="/">Главная</a></li>
        <li><a href="{% url 'courses:list' %}">Курсы</a></li>
        <li><a href="#">О нас</a></li>
    </ul>
</nav>

training_website/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
<div id="container">
    <!-- Навигационная панель -->
    {% include '_navbar.html' %}
    <!-- Основное содержимое -->
    <div id="content">{% block content %}{% endblock %}</div>
    <!-- Нижний колонтитул -->
    {% include '_footer.html' %}
</div>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>